name: CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 🧱 Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 🧹 Step 2: Clean old Chrome processes
      - name: Kill stale Chrome processes
        run: sudo pkill chrome || true

      # ☕ Step 3: Setup Java (for Maven + Cucumber)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 🧩 Step 4: Cache Maven dependencies for faster builds
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # 🧰 Step 5: Build project
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # 🧪 Step 6: Run Cucumber Tests
      # Replace `com.test.runner.TestRunner` with your actual TestRunner class
      - name: Run Tests
        env:
          headless: "true"  # ✅ enables headless mode in BaseClass
        run: mvn test -Dcucumber.options="--tags @Smoke" -Dtest=com.test.runner.TestRunner

      # 📊 Step 7: Upload Cucumber HTML Report
      # Adjust path if your reports are generated elsewhere
      - name: Upload Cucumber HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-reports/

      # 📸 Step 8: Upload Screenshots (from your BaseClass or Hooks)
      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: C:\\Users\\malbert\\Desktop\\screenshots\\WebSample\\Screenshots/
          # 👆 Update this path to where your code saves screenshots (e.g., ./Screenshots)
